doctrine:
    dbal:
        dbname: '%env(resolve:DATABASE_TABLE)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASS)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'
        server_version: '%env(resolve:DATABASE_VERSION)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            YrialSimrandom:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/ORM/Mapping'
                prefix: 'Yrial\Simrandom\Domain\Entity'
                alias: YrialSimrandom
