yrial_simrandom:
  generator:
    randomizers:
      rooms:
        min: 3
        max: 15
      budget:
        min: 20000
        max: 400000
      letter:
        start: "A"
        end: "Z"
      buildings: [ 'Bibliothèque','Musée','Piscine','Salle de sport','Plage','Parc','Parc national','Bar','Bar cocktail','Onsen','Jardin communautaire','Espace de vente','Espace de création','Clinique vétérinaire','Conservatoire de musique, des arts dramatiques et picturaux','Observatoire astronomique' ]
      colors:
        - name: blanc
          weight: 2
        - name: gris
          weight: 1
        - name: noir
          weight: 1
        - name: marron clair
          weight: 2
        - name: marron foncé
          weight: 1
        - name: jaune
          weight: 1
        - name: rouge
          weight: 1
        - name: bleu
          weight: 1
        - name: rose mauve violet
          weight: 1
        - name: vert
          weight: 1
        - name: orange
          weight: 1
    challenges:
      - { id: 1, name: Construction, randomizers: [ rooms, colors, budget, letter, buildings ] }