name: PHP Composer and Tests

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Generate .env file
        shell: bash
        run: |
          echo DATABASE_TABLE="test_yrial" > .env.test
          echo DATABASE_DRIVER="pdo_sqlite" >> .env.test
          echo DATABASE_PATH="%kernel.cache_dir%/test.db" >> .env.test
          cat .env.test

      - name: Init Test Env
        run: composer dump-env test

      - name: check .env file
        shell: bash
        run: |
          cat .env.local.php

      - name: Init Test DB
        run: php bin/console --env=test d:d:c

      - name: Init Schema
        run: php bin/console --env=test d:s:c

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          php_version: 8.1.4
          php_extensions: xdebug
        env:
          XDEBUG_MODE: coverage
