name: PHP Composer and Tests

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - uses: php-actions/composer@v5

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: tests/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text
